#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/core/runtime:3.1-buster-slim AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build
WORKDIR /src
COPY ["Starwars.Consumer/Starwars.Consumer.csproj", "Starwars.Consumer/"]
COPY ["Starwars.Core.Config/Starwars.Core.Config.csproj", "Starwars.Core.Config/"]
RUN dotnet restore "Starwars.Consumer/Starwars.Consumer.csproj"
COPY . .
WORKDIR "/src/Starwars.Consumer"
RUN dotnet build "Starwars.Consumer.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Starwars.Consumer.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Starwars.Consumer.dll"]